bridges = []


[[agents]]
id = "Geos"
name = "HoloTesterOne"
public_address = "HcSCjrze6W6ITpzau65aeAYbAiN5ogbmnF9O6Kx8NUWPjfqwfz5v4OuoZfnvihi"
keystore_file = "/home/holo/.config/holochain/keys/HcSCjrze6W6ITpzau65aeAYbAiN5ogbmnF9O6Kx8NUWPjfqwfz5v4OuoZfnvihi"

[[dnas]]
id = "HoloGeosDNA"
file = "/home/holo/projects/geosproject/src/hApp/dist/hApp.dna.json"
hash = "QmeQUS7nFpfTYf41deETWvB98jfuqbaquUuhWgTqNajwMJ"

[[instances]]
id = "GeosInstance1"
agent = "Geos"
dna = "HoloGeosDNA"
    [instances.storage]
    type = "file"
    path = "/home/holo/.config/holochain/storage"

[[interfaces]]
admin = true
id = "websocket interface"
    [interfaces.driver]
    port = 3000
    type = "websocket"

[[interfaces]]
admin = true
id = "http interface"
    [[interfaces.instances]]
    id = "GeosInstance1"
    [interfaces.driver]
    port = 4000
    type = "http"

[logger]
type = "debug"
    [[logger.rules.rules]]
    color = "red"
    exclude = false
    pattern = "^err/"

    [[logger.rules.rules]]
    color = "white"
    exclude = false
    pattern = "^debug/dna"

    [[logger.rules.rules]]
    exclude = false
    pattern = ".*"
